main.py
from flask import Flask
from views import views

app = Flask(__name__)

app.register_blueprint(views)

if __name__ == '__main__':
    app.run(debug=True)

views.py
from flask import Blueprint, render_template, request
import asyncio
from utils import extract_ids, extract_ref_alt, get_frequencies, process_vcf
from api_getters import get_snp_summary, fetch_all_variations

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template('home.html')


@views.route('/consult', methods=['GET', 'POST'])
def consult():
    if request.method == 'POST':
        upload_file = request.files.get('search')

        if not upload_file:
            return render_template('consult.html', error="Escolha um arquivo VCF")

        vcf_df = process_vcf(upload_file)
        showed_vcf = vcf_df.iloc[:500]
        table_html = showed_vcf.to_html(classes='table table-striped ', index=False, header=True)

        return render_template('consult.html', table_html=table_html)

    return render_template('consult.html')


@views.route('/anotation', methods=['GET', 'POST'])
def anotation():
    data = []
    MIN_SHOW = 0
    MAX_SHOW = 25

    variation_headers = {
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    if request.method == 'POST':
        upload_file = request.files.get('search')

        if not upload_file:
            return render_template('search.html', error="Escolha um arquivo VCF")

        file_content = upload_file.read().decode('utf-8')

        ids = extract_ids(file_content)
        ref_alt = extract_ref_alt(file_content)

        showed_ids = ids[MIN_SHOW:MAX_SHOW]
        showed_ref_alt = ref_alt[MIN_SHOW:MAX_SHOW]

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        data = loop.run_until_complete(fetch_all_variations(showed_ids, variation_headers))

        snp_data = []
        for snp_id in showed_ids:
            snp_id = ''.join(filter(str.isdigit, snp_id))
            snp_info = loop.run_until_complete(get_snp_summary(snp_id))
            snp_data.append(snp_info)

        studies = ['1000Genomes', 'ExAC', 'GnomAD', 'GnomAD_exomes', 'ALFA', 'OPMEDi']
        frequencies = get_frequencies(snp_data, studies)

        return render_template('search.html', data=data, frequencies=frequencies, ref_alt=showed_ref_alt)

    return render_template('search.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">
        <link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"
              rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
              rel="stylesheet">
        <title>
            {% block title %}Home{% endblock %}
        </title>
        <style>
        body {
            font-family: 'Roboto', sans-serif;
        }

            table th {
                text-align: left;
            }
        </style>
    </head>
    <body>
        <header>
            <nav class="navbar justify-content-md-center navbar-light bg-light ">
                <div>
                    <a class="navbar-brand" href="{{ url_for("views.home") }}">
                        <img src="{{ url_for('static', filename='images/home.svg') }}"
                             width="80"
                             height="40"
                             alt="">
                    </a>
                </div>
            </nav>
        </header>
        <div>
            {% block content %}{% endblock %}
        </div>
        <footer>
            <div class="container">
                <footer class="py-3 my-4">
                    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                        <li class="nav-item">
                            <a href="#" class="nav-link px-2 text-body-secondary">
                                Este produto está em estado de MVP e em fase 1 de testes com os usuários selecionados.
                                Todo feedback é bem-vindo para melhorias em futuras atualizações.
                            </a>
                        </ul>
                        <p class="text-center text-body-secondary">
                            MATERIAL DE USO INTERNO.
                        </p>
                        <p class="text-center text-body-secondary">© GETVAR 2024</p>
                    </footer>
                </div>
            </footer>
            <!-- jQuery e DataTables JS -->
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                    crossorigin="anonymous"></script>
            <script>
    $(document).ready(function() {
        // Ativa o DataTable para a tabela gerada
        var table = $('table').DataTable({
            "paging": true,  // Habilita paginação
            "searching": true,  // Habilita o filtro de pesquisa
            "ordering": true   // Habilita a ordenação das colunas
        });

        // Atualiza o valor máximo de DP
        $('#dp-max').on('input', function() {
            var dpMax = $(this).val();
            $('#dp-value').text('0 - ' + dpMax);
            filterTable();
        });

        // Atualiza o valor máximo de AF
        $('#af-max').on('input', function() {
            var afMax = $(this).val();
            $('#af-value').text('0 - ' + afMax);
            filterTable();
        });

        // Atualiza o filtro quando o valor mínimo for alterado
        $('#dp-min').on('input', function() {
            filterTable();
        });

        $('#af-min').on('input', function() {
            filterTable();
        });

        // Função para aplicar o filtro
        function filterTable() {
            table.rows().every(function(rowIdx, tableLoop, rowLoop) {
                var row = this.data();
                var dp = parseInt(row[7]);  // Coluna DP
                var af = parseFloat(row[8]);  // Coluna AF
                var dpMin = $('#dp-min').val();  // Valor mínimo DP
                var afMin = $('#af-min').val();  // Valor mínimo AF
                var dpMax = $('#dp-max').val();  // Valor máximo DP
                var afMax = $('#af-max').val();  // Valor máximo AF

                // Verifica se os valores estão dentro do intervalo
                if (dp >= dpMin && dp <= dpMax && af >= afMin && af <= afMax) {
                    $(this.node()).show();
                } else {
                    $(this.node()).hide();
                }
            });
        }
    });
            </script>
        </body>
    </html>

templates/consult.html
{% extends 'base.html' %}
{% block title %}Search{% endblock %}
{% block content %}
    <header class="py-3 mb-3 container">
        <p>Insira o arquivo VCF</p>
        <div class="d-flex align-items-center">
            <form class="w-100 me-3 d-flex"
                  role="search"
                  method="POST"
                  enctype="multipart/form-data">
                <input type="file"
                       name="search"
                       id="search"
                       class="form-control"
                       placeholder="Search the sequences"
                       aria-label="Search" />
                <button type="submit" class="btn btn-primary me-2 ms-2">Consultar</button>
            </form>
        </div>
    </header>
    {% if error %}<div class="error container">{{ error }}</div>{% endif %}
    {% if table_html %}
        <div class="container">
            <!-- Linha para DP (min e max) -->
            <div class="row mb-3">
                <div class="col-md-6">
                    <label for="dp-min" class="form-label">Minimum DP:</label>
                    <input type="number"
                           id="dp-min"
                           class="form-control"
                           min="0"
                           max="100"
                           value="0"
                           step="1">
                </div>
                <div class="col-md-6">
                    <label for="dp-max" class="form-label">Maximum DP:</label>
                    <input type="number"
                           id="dp-max"
                           class="form-control"
                           min="0"
                           max="300"
                           value="300"
                           step="1">
                </div>
            </div>
            <!-- Linha para AF (min e max) -->
            <div class="row mb-3">
                <div class="col-md-6">
                    <label for="af-min" class="form-label">Minimum AF:</label>
                    <input type="number"
                           id="af-min"
                           class="form-control"
                           min="0"
                           max="1"
                           value="0"
                           step="0.01">
                </div>
                <div class="col-md-6">
                    <label for="af-max" class="form-label">Maximum AF:</label>
                    <input type="number"
                           id="af-max"
                           class="form-control"
                           min="0"
                           max="1"
                           value="1"
                           step="0.01">
                </div>
            </div>
        </div>
        <div class="container text-left">{{ table_html|safe }}</div>
    {% endif %}
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <section class="jumbotron text-center mt-5">
        <div class="container">
            <img src="{{ url_for('static', filename='images/main_logo.png') }}"
                 width="300"
                 height="200"
                 alt="">
            <p class="lead text-muted mb-5">Uma ferramenta para consulta e anotação de arquivos VCF</p>
            <div class="d-flex justify-content-center">
                <div class="d-flex flex-column w-50 ">
                    <a href="{{ url_for("views.consult") }}"
                       class="btn btn-outline-primary btn-lg btn-block mb-3">Consultar</a>
                    <a href="{{ url_for("views.anotation") }}"
                       class="btn btn-outline-success btn-lg btn-block">Anotar</a>
                </div>
            </div>
        </div>
    </section>
    <div class="container d-flex justify-content-center">
        <video autoplay muted loop width = "400" height = "270">
            <source src="{{ url_for('static', filename='videos/vid_logo.mp4') }}"
                    type="video/mp4">
        </video>
    </div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% block title %}Search{% endblock %}
{% block content %}
    <header class="py-3 mb-3 container">
        <p>Insira o arquivo VCF</p>
        <div class="d-flex align-items-center">
            <form class="w-100 me-3 d-flex"
                  role="search"
                  method="POST"
                  enctype="multipart/form-data">
                <input type="file"
                       name="search"
                       id="search"
                       class="form-control"
                       placeholder="Search the sequences"
                       aria-label="Search">
                <button type="submit" class="btn btn-success me-2 ms-2">Anotar</button>
            </form>
        </div>
    </header>
    <body>
        {% if error %}<div class="error container">{{ error }}</div>{% endif %}
        {% if data %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">CHROM</th>
                        <th scope="col">REF</th>
                        <th scope="col">ALT</th>
                        <th scope="col">Population Allele Frequency</th>
                        <th scope="col">Var Class</th>
                        <th scope="col">Most Severe Consequence</th>
                        <th scope="col">Clinical Significance</th>
                        <th scope="col">Synonyms</th>
                        <th scope="col">Ambiguity</th>
                        <th scope="col">Minor Allele</th>
                        <th scope="col">Mappings</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in data %}
                        <tr>
                            <td>{{ data['name'] }}</td>
                            {% for _, values in ref_alt[loop.index0].items() %}<td>{{ values }}</td>{% endfor %}
                            <td>
                                {% for study, freq in frequencies[loop.index0].items() %}
                                    <div>
                                        <strong>{{ study }}</strong>: {{ freq }}
                                    </div>
                                {% endfor %}
                            </td>
                            <td>{{ data['var_class'] }}</td>
                            <td>{{ data['most_severe_consequence'] }}</td>
                            <td>
                                {{ data['clinical_significance'] | join("<br>") | safe or 'N/A' }}
                            </td>
                            <td>
                                {{ data['synonyms']  | join("<br>") | safe }}
                            </td>
                            <td>{{ data['ambiguity'] }}</td>
                            <td>{{ data['minor_allele'] or 'N/A' }}</td>
                            <td>
                                {% for mapping in data['mappings'] %}
                                    <div>
                                        <strong>Allele String:</strong> {{ mapping['allele_string'] }}
                                        <br>
                                        <strong>Coord System:</strong> {{ mapping['coord_system'] }}
                                        <br>
                                        <strong>Ancestral Allele:</strong> {{ mapping['ancestral_allele'] }}
                                        <br>
                                        <strong>Location:</strong> {{ mapping['location'] }}
                                    </div>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </body>
{% endblock %}